spring:
  application:
    name: housing-service
  mvc:
    servlet:
      path: /housing-service

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka