spring:
  application:
    name: book-store

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  circuitbreaker:
    enabled: true
