server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aprilhucode/CloudConfig.git
          clone-on-start: true
          skip-ssl-validation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
